# Generated by Django 2.1.3 on 2018-11-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nota',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='telefono',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='ciudad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='codigopostal',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='direccion',
            field=models.CharField(default='', max_length=250),
        ),
    ]
