# Generated by Django 2.1.3 on 2018-12-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181126_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='nota',
            field=models.TextField(blank=True, default=''),
        ),
    ]
