# Generated by Django 2.1.3 on 2019-01-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181214_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ciudad',
            field=models.CharField(choices=[('Puerto Rico', 'Puerto Rico'), ('Garuhape', 'Garuhape'), ('San Alberto Puerto', 'San Alberto Puerto'), ('San Alberto Colonia', 'San Alberto Colonia')], default='', max_length=100),
        ),
    ]
