# Generated by Django 2.1.3 on 2018-11-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20181115_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
