# Generated by Django 2.1.3 on 2018-12-17 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='url_imagen',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 17, 43, 23, 862052)),
        ),
    ]
