# Generated by Django 2.1.3 on 2019-02-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20190111_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigobarra',
            field=models.CharField(default='', max_length=14),
        ),
    ]
